### ISSUE TITLE
Distorted image on Portrait mode

### ISSUE THREAD

**Issue by noobiwan** [phonegap/phonegap-plugin-barcodescanner#37]
When I call the scan method of the plugin in portrait mode the image gets squeezed, but it looks fine on landscape mode. I'm running Android 5.0.2 on HTC ONE. I also tested on Galaxy S5 and it shows the same problem. Is this a know issue? Any suggestions on how to fix it?

**Comment by surajpindoria** [comment]
Hi @fromvega, are you still seeing this issue? I am unable to reproduce it.

**Comment by fromvega** [comment]
Yes @surajpindoria, I'm still seeing a squeezed image on portrait mode. I just downloaded the plugin again to make sure I got the last version (phonegap plugin add phonegap-plugin-barcodescanner)

I just included the plugin and called cordova.plugins.barcodeScanner.scan() with no configuration. Am I missing something?

**Comment by surajpindoria** [comment]
When I call cordova.plugins.barcodeScanner.scan() without any parameters it is not even launching the camera for me. Can you try passing in a success callback and see if that does anything different?

**Comment by fromvega** [comment]
I'm sorry, I did pass a callback. What I meant by "no configuration" is that I'm not messing with the plugin itself, like barcodescanner.js or plugin.xml files.

**Comment by fromvega** [comment]
Funny thing. I'm using Ionic to develop my app. When I build the app myself through the command line and then run it on my Android device, the camera gets distorted in portrait mode. But, using the Ionic deploy system, the camera works fine. Any clue why? I'm not sure which version of the plugin the Ionic system is using. The version in my setup is: phonegap-plugin-barcodescanner 4.0.1

I noticed another thing, it's not just the image of the camera that's different. When I build the app myself, my version of the plugin rotates the text to match the phone orientation. With the Ionic build the text DOESN'T rotate, it's always in landscape mode. So what do you think? Does it mean the Ionic deploy is using a different configuration or an old version of the plugin that locks the screen in landscape mode?

**Comment by surajpindoria** [comment]
That could be what's happening. Can you post a photo of what you are seeing as I am unable to reproduce?

**Comment by galuhp** [comment]
@noobiwan i also got this issue. work fine at first development. but got this distorted screen at protrait. no problem at landscape mode
here i attach the screen capture

![screenshot_2015-08-28-10-00-13](https://cloud.githubusercontent.com/assets/1094479/9538172/b6a12d9e-4d6b-11e5-85b2-a1b896bf22f5.png)

**Comment by moonlight2** [comment]
I have the same issue on Android 4.3 and above.

**Comment by danzero** [comment]
Did anyone discover a fix for this? I'm also getting a squashed image in portrait mode. This is a photo from my camera:
![imag0281](https://cloud.githubusercontent.com/assets/9921077/10745001/f85e6236-7ca2-11e5-8a3e-1d5032e12d2d.jpg)

And this is one from the BarcodeScanner:
![screenshot_2015-10-27-11-55-46](https://cloud.githubusercontent.com/assets/9921077/10745006/02ae1420-7ca3-11e5-86ce-e577b1d1175a.png)

Landscape seems to be fine though. I'm using the HTC One M7

**Comment by koga73** [comment]
I'm experiencing the same issue. App built with Ionic via CLI running on Android 5.1.1

**Comment by fgrs** [comment]
same distortion in portrait

**Comment by deyoppe** [comment]
I am having the same issue. I tested on three devices
* Samsung S3 (i9300) - 6.0.1 (CM13)
* Samsung S3 (i9300) - 4.4.4 (CM11)
* Samsung S3 (i9300) - 4.3 (Official)

On official Android the scanner seems to be working correctly.
On CM Android, only landscape version works. Portrait mode however seems to have the same issue as @galuhp 
It seems to be an issue with how CyanogenMod handles the camera. Can anyone else confirm whether this is only related to custom ROMs?

**Comment by koga73** [comment]
I am not running Cyanogenmod. I am experiencing the issue on a stock Galaxy S6 Edge running Android 5.1.1

**Comment by alexisvincent** [comment]
Me too

**Comment by Aerue** [comment]
Experiencing issue too on Mi-4c, Android 5.1.1, MIUI 7-6.1.21

**Comment by steffchep** [comment]
Also seeing this, S5 Android 5.1 (as well as 6)

**Comment by sarangan12** [comment]
This should be fixed with the latest telerik code merge. Resolving this issue. If you still find this issue, please reopen it

**Comment by mindr242** [comment]
I still have this issue with v.6.0.0 of this plugin and Android 5.1.1.

The image in portrait is distorted.

**Comment by BigMurry** [comment]
I still have this issue with v6.0.1 for portrait mode.
ps: Build for Android 5.1.1

**Comment by thomaspessato** [comment]
I'm having this issue too. Build for Android 6.0.1.

**Comment by HarleyTan** [comment]
how to fix this?
