### ISSUE TITLE
Ios 11 crash because of no permission dialog

### ISSUE THREAD

**Issue by badpenguin** [phonegap/phonegap-plugin-barcodescanner#622]
The plugin crashes under ios 11 when building using remote phonegap; no dialog for pemission is showed.

I've the camera plugin installed and working but seems unrelated.

I fixed by installing this other plugin:
cordova-plugin-ios-camera-permissions ^1.2.0

Perhaps add a section "Ios quirks" to the docs.

**Comment by jcesarmobile** [comment]
It's already mentioned, but not in the quirks section, maybe we should move it there as in the core plugins

**Comment by okandeb** [comment]
Same problem.

**Comment by nealchecka** [comment]
Hey badpenguin, what did you exactly do to get it to work? I tried adding the plugin you mentioned by doing the following:
` <plugin name="cordova-plugin-ios-camera-permissions" spec="^1.2.0"/>`

Am I missing something?

**Comment by okandeb** [comment]
Downgraded to 7.0.2. It works. No need permission plugin.

**Comment by nealchecka** [comment]
Downgrading to 7.0.2 makes it work on ios, but in Android it's not responsive. It doesn't crash but it doesn't open the camera to scan a barcode.

**Comment by jcesarmobile** [comment]
I've released a 7.0.4 version without the commit that removed the usage description variable so it doesn't crash if you don't set it.

But I'm going to apply it again for 7.1.0, from 7.1.0 you will have to set the usage description using edit-config tag, as on all core plugins and it won't be set with a default value, so you will have to set it to avoid the crash.

```
<edit-config target="NSCameraUsageDescription" file="*-Info.plist" mode="merge">
    <string>To scan barcodes</string>
</edit-config>
```

**Comment by sebikovacs** [comment]
This is still happening.

@jcesarmobile what I did was to create the demo app as illustrated in the [cordova documentation](https://cordova.apache.org/docs/en/latest/guide/cli/index.html), add the barcodescanner plugin and run the scan function from the Safari develop console. The app crashes every time.

PS: I tried adding the `NSCameraUsageDescription`, and the cordova-plugin-ios-camera-permissions but to no avail.

Is there anything I've missed?

**Comment by jcesarmobile** [comment]
Are you using 7.1.0?

Can you explain the "PS: I tried adding the NSCameraUsageDescription, and the cordova-plugin-ios-camera-permissions but to no avail."

I've tried and with the edit-config tag it works fine

**Comment by jcesarmobile** [comment]
I've released 7.1.1 that will return an error if NSCameraUsageDescription is not set.
Please, update and if you are still getting crashes it won't be related to NSCameraUsageDescription not being set, so report a new issue with more information.
